#!/usr/bin/env Rscript
# Test script to validate sub.pop parameter compatibility with InSilicoVA

library(InSilicoVA)
library(openVA)

# Load the example data from openVA package
data(RandomVA5)

# Create dummy subpopulation labels
# Using 1s and 2s as would be generated by our Python code
n_samples <- nrow(RandomVA5)
subpop_labels <- c(rep(1, floor(n_samples/2)), rep(2, ceiling(n_samples/2)))

cat("Testing InSilicoVA with sub.pop parameter...\n")
cat("Data shape:", dim(RandomVA5), "\n")
cat("Subpop labels length:", length(subpop_labels), "\n")
cat("Unique subpop values:", unique(subpop_labels), "\n\n")

# Test 1: Basic sub.pop parameter acceptance
tryCatch({
    cat("Test 1: Testing if sub.pop parameter is accepted...\n")
    fit_with_subpop <- codeVA(
        data = RandomVA5,
        model = "InSilicoVA",
        sub.pop = as.character(subpop_labels),  # Try as character first
        Nsim = 1000,  # Use fewer iterations for quick test
        auto.length = FALSE
    )
    cat("✓ SUCCESS: sub.pop parameter accepted with character labels\n\n")
    print(summary(fit_with_subpop))
}, error = function(e) {
    cat("✗ Character labels failed:", e$message, "\n")
    
    # Try with numeric labels
    tryCatch({
        cat("Test 1b: Trying numeric labels...\n")
        fit_with_subpop <- codeVA(
            data = RandomVA5,
            model = "InSilicoVA",
            sub.pop = subpop_labels,  # Try as numeric
            Nsim = 1000,
            auto.length = FALSE
        )
        cat("✓ SUCCESS: sub.pop parameter accepted with numeric labels\n\n")
        print(summary(fit_with_subpop))
    }, error = function(e2) {
        cat("✗ Numeric labels also failed:", e2$message, "\n")
        cat("ERROR: sub.pop parameter not supported or format issue\n")
    })
})

# Test 2: Compare with and without sub.pop
cat("\nTest 2: Comparing results with and without sub.pop...\n")

# Run without sub.pop
fit_without <- codeVA(
    data = RandomVA5,
    model = "InSilicoVA",
    Nsim = 1000,
    auto.length = FALSE
)

# Get CSMFs
csmf_without <- getCSMF(fit_without)
cat("CSMF without sub.pop (top 5):\n")
print(head(csmf_without, 5))

cat("\n✓ All tests completed. Check output above for results.\n")